import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { CheckCircle, AlertTriangle, Brain, Activity, Clock, TrendingUp, Download, RotateCcw, Zap } from 'lucide-react';
import { Button } from '../ui/button';
import { analyzeEMGHealth, type EMGHealthInsight } from '../../lib/emg/emg-ai';
import type { ProcessedEMG, FatigueLevel } from '../../lib/emg/emg-processing';

interface SessionStats {
  durationSeconds: number;
  totalReadings: number;
  avgSignal: number;
  peakSignal: number;
  avgFatigueIndex: number;
  strainEvents: number;
  finalFatigueLevel: FatigueLevel;
  activityType: string;
}

interface Props {
  history: ProcessedEMG[];
  durationSeconds: number;
  activityType: string;
  onNewSession: () => void;
}

function computeStats(history: ProcessedEMG[], durationSeconds: number, activityType: string): SessionStats {
  if (!history.length) return {
    durationSeconds, totalReadings: 0, avgSignal: 0, peakSignal: 0,
    avgFatigueIndex: 0, strainEvents: 0, finalFatigueLevel: 'low', activityType,
  };
  const signals = history.map(h => h.normalized);
  const avgSignal = signals.reduce((a, b) => a + b, 0) / signals.length;
  const peakSignal = Math.max(...signals);
  const avgFatigueIndex = history.reduce((a, h) => a + h.fatigueIndex, 0) / history.length;
  const strainEvents = history.filter(h => h.strainDetected).length;
  const finalFatigueLevel = history[history.length - 1]?.fatigueLevel ?? 'low';
  return { durationSeconds, totalReadings: history.length, avgSignal, peakSignal, avgFatigueIndex, strainEvents, finalFatigueLevel, activityType };
}

const fatigueColor = {
  low:      { text: 'text-green-600',  bg: 'bg-green-50',  border: 'border-green-200',  label: 'Low'      },
  moderate: { text: 'text-yellow-600', bg: 'bg-yellow-50', border: 'border-yellow-200', label: 'Moderate' },
  high:     { text: 'text-red-600',    bg: 'bg-red-50',    border: 'border-red-200',    label: 'High'     },
};

const riskColor = {
  low:      { text: 'text-green-700',  bg: 'bg-green-100'  },
  moderate: { text: 'text-yellow-700', bg: 'bg-yellow-100' },
  high:     { text: 'text-red-700',    bg: 'bg-red-100'    },
};

export function EMGSessionReport({ history, durationSeconds, activityType, onNewSession }: Props) {
  const [insight, setInsight] = useState<EMGHealthInsight | null>(null);
  const [loading, setLoading] = useState(true);
  const stats = computeStats(history, durationSeconds, activityType);
  const fc = fatigueColor[stats.finalFatigueLevel];

  useEffect(() => {
    analyzeEMGHealth({
      fatigueLevel: stats.finalFatigueLevel,
      fatigueIndex: stats.avgFatigueIndex,
      strainDetected: stats.strainEvents > 3,
      peakSignals: history.filter(h => h.normalized > 0.7).map(h => h.normalized),
      sessionDurationSeconds: durationSeconds,
      averageFatigueIndex: stats.avgFatigueIndex,
    }).then(setInsight).finally(() => setLoading(false));
  }, []);

  const handleExport = () => {
    const lines = [
      '=== PIXAL HEALTH — EMG SESSION REPORT ===',
      `Date: ${new Date().toLocaleString()}`,
      `Activity: ${activityType}`,
      `Duration: ${formatDuration(durationSeconds)}`,
      `Total Readings: ${stats.totalReadings}`,
      '',
      '--- MUSCLE METRICS ---',
      `Avg Signal Intensity: ${(stats.avgSignal * 100).toFixed(1)}%`,
      `Peak Signal: ${(stats.peakSignal * 100).toFixed(1)}%`,
      `Avg Fatigue Index: ${(stats.avgFatigueIndex * 100).toFixed(1)}%`,
      `Final Fatigue Level: ${stats.finalFatigueLevel.toUpperCase()}`,
      `Strain Events: ${stats.strainEvents}`,
      '',
      '--- AI HEALTH ANALYSIS ---',
      insight ? `Status: ${insight.muscleHealthStatus}` : 'N/A',
      insight ? `Risk Level: ${insight.riskLevel.toUpperCase()}` : '',
      insight ? `Recovery Time: ${insight.recoveryTime}` : '',
      '',
      '--- RECOMMENDATIONS ---',
      ...(insight?.recommendations.map((r, i) => `${i + 1}. ${r}`) ?? []),
      '',
      'Generated by Pixal Health EMG Monitor',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `emg-report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="p-2 rounded-xl bg-[#4A9B8E20] text-[#4A9B8E]">
            <Activity className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-base font-bold text-[#2D3748] font-nunito">Session Report</h2>
            <p className="text-xs text-[#718096]">{new Date().toLocaleString()}</p>
          </div>
        </div>
        <div className="flex gap-2">
          <Button size="sm" variant="outline" onClick={handleExport} className="h-8 text-xs border-[#E2E8F0]">
            <Download className="w-3.5 h-3.5 mr-1" /> Export
          </Button>
          <Button size="sm" onClick={onNewSession} className="h-8 text-xs bg-[#4A9B8E] hover:bg-[#3d8578] text-white">
            <RotateCcw className="w-3.5 h-3.5 mr-1" /> New Session
          </Button>
        </div>
      </div>

      {/* No data warning */}
      {stats.totalReadings === 0 && (
        <div className="p-3 bg-yellow-50 border border-yellow-200 rounded-xl text-xs text-yellow-700">
          ⚠️ No readings captured. Make sure you are connected and session ran for at least a few seconds.
        </div>
      )}

      {/* Stats grid */}
      <div className="grid grid-cols-2 gap-3">
        <StatCard icon={<Clock className="w-4 h-4" />} label="Duration" value={formatDuration(durationSeconds)} />
        <StatCard icon={<Activity className="w-4 h-4" />} label="Readings" value={stats.totalReadings.toString()} />
        <StatCard icon={<TrendingUp className="w-4 h-4" />} label="Peak Signal" value={`${(stats.peakSignal * 100).toFixed(0)}%`} />
        <StatCard icon={<Zap className="w-4 h-4" />} label="Strain Events" value={stats.strainEvents.toString()} alert={stats.strainEvents > 3} />
      </div>

      {/* Fatigue summary */}
      <div className={`p-4 rounded-xl border ${fc.bg} ${fc.border}`}>
        <div className="flex items-center justify-between mb-3">
          <span className="text-sm font-semibold text-[#2D3748]">Muscle Fatigue Summary</span>
          <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${fc.bg} ${fc.text} border ${fc.border}`}>
            {fc.label}
          </span>
        </div>
        <div className="space-y-2">
          <MiniBar label="Avg Intensity" value={stats.avgSignal} color="#4A9B8E" />
          <MiniBar label="Avg Fatigue" value={Math.min(1, stats.avgFatigueIndex * 3.33)} color={
            stats.finalFatigueLevel === 'high' ? '#E53E3E' :
            stats.finalFatigueLevel === 'moderate' ? '#D69E2E' : '#38A169'
          } />
          <MiniBar label="Peak Load" value={stats.peakSignal} color="#805AD5" />
        </div>
      </div>

      {/* AI Analysis */}
      <div className="p-4 bg-white rounded-xl border border-[#E2E8F0]">
        <div className="flex items-center gap-2 mb-3">
          <Brain className="w-4 h-4 text-[#4A9B8E]" />
          <span className="text-sm font-bold text-[#2D3748]">
            {loading ? 'Generating AI Analysis…' : `${insight?.source === 'ai' ? 'AI' : 'Health'} Analysis`}
          </span>
          {loading && <div className="w-3.5 h-3.5 border-2 border-[#4A9B8E]/30 border-t-[#4A9B8E] rounded-full animate-spin ml-auto" />}
        </div>
        {insight && !loading && (
          <div className="space-y-3">
            <div className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold ${riskColor[insight.riskLevel].bg} ${riskColor[insight.riskLevel].text}`}>
              {insight.riskLevel === 'low' ? <CheckCircle className="w-3.5 h-3.5" /> : <AlertTriangle className="w-3.5 h-3.5" />}
              {insight.riskLevel.toUpperCase()} RISK
            </div>
            <p className="text-sm text-[#2D3748] font-medium">{insight.muscleHealthStatus}</p>
            <div className="space-y-1.5">
              <p className="text-xs font-semibold text-[#4A5568] uppercase tracking-wide">Recommendations</p>
              {insight.recommendations.map((r, i) => (
                <div key={i} className="flex items-start gap-2 text-xs text-[#4A5568]">
                  <CheckCircle className="w-3.5 h-3.5 text-[#4A9B8E] mt-0.5 shrink-0" />
                  {r}
                </div>
              ))}
            </div>
            {insight.recoveryTime && (
              <div className="flex items-center gap-2 pt-2 border-t border-[#E2E8F0]">
                <Clock className="w-3.5 h-3.5 text-[#718096]" />
                <span className="text-xs text-[#718096]">Estimated recovery: <strong>{insight.recoveryTime}</strong></span>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Health Score */}
      <OverallHealthScore stats={stats} />
    </motion.div>
  );
}

function OverallHealthScore({ stats }: { stats: SessionStats }) {
  const score = Math.round(
    100 -
    (stats.avgFatigueIndex * 100 * 0.4) -
    (Math.min(stats.strainEvents, 10) * 3) -
    (stats.finalFatigueLevel === 'high' ? 20 : stats.finalFatigueLevel === 'moderate' ? 10 : 0)
  );
  const clamped = Math.max(0, Math.min(100, score));
  const color = clamped >= 70 ? '#38A169' : clamped >= 40 ? '#D69E2E' : '#E53E3E';
  const label = clamped >= 70 ? 'Good' : clamped >= 40 ? 'Fair' : 'Poor';
  return (
    <div className="p-4 bg-white rounded-xl border border-[#E2E8F0] flex items-center gap-4">
      <svg width="64" height="64" viewBox="0 0 64 64">
        <circle cx="32" cy="32" r="26" fill="none" stroke="#E2E8F0" strokeWidth="6" />
        <circle cx="32" cy="32" r="26" fill="none" stroke={color} strokeWidth="6"
          strokeDasharray={`${(clamped / 100) * 163} 163`} strokeLinecap="round"
          transform="rotate(-90 32 32)" style={{ transition: 'stroke-dasharray 1s ease' }} />
        <text x="32" y="36" textAnchor="middle" fontSize="14" fontWeight="700" fill={color}>{clamped}</text>
      </svg>
      <div>
        <p className="text-sm font-bold text-[#2D3748]">Overall Muscle Health Score</p>
        <p className="text-xs text-[#718096] mt-0.5">This session: <strong style={{ color }}>{label}</strong></p>
        <p className="text-xs text-[#718096] mt-1">Based on fatigue index, strain events, and signal intensity</p>
      </div>
    </div>
  );
}

function StatCard({ icon, label, value, alert }: { icon: React.ReactNode; label: string; value: string; alert?: boolean }) {
  return (
    <div className="p-3 bg-white rounded-xl border border-[#E2E8F0] flex items-center gap-2.5">
      <div className="p-1.5 rounded-lg bg-[#4A9B8E15] text-[#4A9B8E]">{icon}</div>
      <div>
        <p className="text-xs text-[#718096]">{label}</p>
        <p className={`text-sm font-bold ${alert ? 'text-red-500' : 'text-[#2D3748]'}`}>{value}</p>
      </div>
    </div>
  );
}

function MiniBar({ label, value, color }: { label: string; value: number; color: string }) {
  return (
    <div className="flex items-center gap-2">
      <span className="text-xs text-[#718096] w-24 shrink-0">{label}</span>
      <div className="flex-1 h-2 bg-white/60 rounded-full overflow-hidden">
        <div className="h-full rounded-full transition-all duration-700"
          style={{ width: `${Math.round(value * 100)}%`, background: color }} />
      </div>
      <span className="text-xs font-mono text-[#4A5568] w-8 text-right">{Math.round(value * 100)}%</span>
    </div>
  );
}

function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return m > 0 ? `${m}m ${s}s` : `${s}s`;
}
